-- Versión 1 del esquema, congelada en S191. No se edita nunca: los cambios van en esquema/NNN.sql.
--
-- La reciben las bases sin número (PRAGMA user_version = 0), que son todas las anteriores a
-- S191: las de v0.2.0 y las de antes de S159, que no tienen tabla curso. Cada sentencia es la
-- de schema.sql en S191, con su "if not exists": crea lo que falte y no toca lo que ya está.
-- Después PreparadorEsquema sella la base como 1, en la misma transacción.

create table if not exists actividad (duracion_tramos integer not null, repeticiones_por_semana integer not null, requiere_tutor boolean not null, asignatura_id bigint, id integer, codigo varchar(255) not null unique, patron_temporal varchar(255) not null check ((patron_temporal in ('DISTRIBUIDA','AGRUPADA','NEUTRA'))), primary key (id), foreign key (asignatura_id) references asignatura(id));
create table if not exists asignatura (id integer, codigo varchar(255) not null unique, nombre_completo varchar(255) not null, primary key (id));
create table if not exists asignatura_aula_compatible (asignatura_id bigint not null, id integer, tipo_aula varchar(255) not null check ((tipo_aula in ('ORDINARIA','LAB_CIENCIAS','INFORMATICA','TALLER_TEC','TALLER_PLASTICA','GIMNASIO','PISTA','TALLER_FPB','COMUN'))), primary key (id), foreign key (asignatura_id) references asignatura(id) on delete cascade);
create table if not exists aula (capacidad integer, planta integer, id integer, codigo varchar(255) not null unique, edificio varchar(255), sector varchar(255), tipo varchar(255) not null check ((tipo in ('ORDINARIA','LAB_CIENCIAS','INFORMATICA','TALLER_TEC','TALLER_PLASTICA','GIMNASIO','PISTA','TALLER_FPB','COMUN'))), primary key (id));
create table if not exists aula_bloqueada (indice integer not null, actividad_id bigint not null, aula_id bigint not null, id integer, plaza_id bigint not null, primary key (id), foreign key (actividad_id) references actividad(id), foreign key (aula_id) references aula(id), foreign key (plaza_id) references plaza(id));
create table if not exists configuracion (clave varchar(255) not null, valor varchar(255) not null, primary key (clave));
create table if not exists grupo_administrativo (grupo_padre_id bigint, id integer, nivel_id bigint not null, codigo varchar(255) not null unique, tipo varchar(255) not null check ((tipo in ('ORDINARIO','DIVERSIFICACION_PDC','VIRTUAL_OPTATIVA'))), primary key (id), foreign key (grupo_padre_id) references grupo_administrativo(id), foreign key (nivel_id) references nivel(id));
create table if not exists horario_generado (cota_inferior float, objetivo float, fecha_generacion timestamp not null, id integer, estado varchar(255) not null check ((estado in ('BORRADOR','DEFINITIVO','DESCARTADO'))), estado_solver varchar(255) not null, nombre varchar(255) not null, primary key (id));
create table if not exists nivel (orden integer not null, id integer, codigo varchar(255) not null unique, primary key (id));
create table if not exists plaza (actividad_id bigint not null, asignatura_id bigint not null, aula_fija_id bigint, id integer, codigo varchar(255) not null unique, primary key (id), foreign key (actividad_id) references actividad(id) on delete cascade, foreign key (asignatura_id) references asignatura(id), foreign key (aula_fija_id) references aula(id));
create table if not exists plaza_aula_candidata (aula_id bigint not null, plaza_id bigint not null, primary key (aula_id, plaza_id), foreign key (aula_id) references aula(id), foreign key (plaza_id) references plaza(id) on delete cascade);
create table if not exists plaza_profesor (plaza_id bigint not null, profesor_id bigint not null, primary key (plaza_id, profesor_id), foreign key (plaza_id) references plaza(id) on delete cascade, foreign key (profesor_id) references profesor(id));
create table if not exists plaza_subgrupo (plaza_id bigint not null, subgrupo_id bigint not null, primary key (plaza_id, subgrupo_id), foreign key (plaza_id) references plaza(id) on delete cascade, foreign key (subgrupo_id) references subgrupo(id));
create table if not exists profesor (id integer, codigo varchar(255) not null unique, nombre_completo varchar(255) not null, primary key (id));
create table if not exists profesor_restriccion_horaria (peso integer not null, id integer, profesor_id bigint not null, tramo_id bigint not null, motivo varchar(255), tipo varchar(255) not null check ((tipo in ('DURA','BLANDA'))), primary key (id), foreign key (profesor_id) references profesor(id), foreign key (tramo_id) references tramo_semanal(id));
create table if not exists profesor_tutoria (grupo_id bigint not null, profesor_id bigint not null, rol varchar(255) not null check ((rol in ('TUTOR_PRINCIPAL','CO_TUTOR'))), primary key (profesor_id, grupo_id), foreign key (profesor_id) references profesor(id), foreign key (grupo_id) references grupo_administrativo(id) on delete cascade);
create table if not exists sesion (indice integer not null, aula_id bigint not null, horario_id bigint not null, id integer, plaza_id bigint not null, tramo_inicio_id bigint not null, primary key (id), foreign key (aula_id) references aula(id), foreign key (horario_id) references horario_generado(id) on delete cascade, foreign key (plaza_id) references plaza(id), foreign key (tramo_inicio_id) references tramo_semanal(id));
create table if not exists sesion_bloqueada (indice integer not null, actividad_id bigint not null, id integer, tramo_inicio_id bigint not null, primary key (id), foreign key (actividad_id) references actividad(id), foreign key (tramo_inicio_id) references tramo_semanal(id));
create table if not exists subgrupo (id integer, codigo varchar(255) not null unique, primary key (id));
create table if not exists subgrupo_grupo (grupo_id bigint not null, subgrupo_id bigint not null, primary key (grupo_id, subgrupo_id), foreign key (grupo_id) references grupo_administrativo(id), foreign key (subgrupo_id) references subgrupo(id));
create table if not exists tramo_semanal (es_lectivo boolean not null, hora_fin time(0) not null, hora_inicio time(0) not null, orden integer not null, id integer, siguiente_inmediato_id bigint, dia varchar(255) not null check ((dia in ('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES'))), primary key (id), foreign key (siguiente_inmediato_id) references tramo_semanal(id));

-- curso: identidad del fichero (nombre y si está archivado). FILA ÚNICA: el check (id = 1) se añade a mano,
-- como las FK. NO es configuración: no se copia tal cual al duplicar (O-curso, S159).
create table if not exists curso (id integer not null check (id = 1), nombre varchar(9) not null, archivado boolean not null, primary key (id));
